#!/usr/bin/env python3
"""
check_nocheckpoint_switches.py -- is a -nocheckpoint routine list consistent
with the adjoint-mode switches?

An adjoint-mode switch (useGMRediInAdMode, useKPPinAdMode,
useApproxAdvectionInAdMode, ...) changes inAdMode and some package flags at the
start of every backward step, through AUTODIFF_INADMODE_SET_TAP_B, and restores
them at its end. It reaches the adjoint only where Tapenade re-runs a routine's
primal inside the backward sweep, that is in joint (checkpointed) mode. A
routine differentiated in split mode (-nocheckpoint) replays the tape of the
forward sweep instead, recorded with the switches in their forward-mode state.

A list build therefore gives the checkpoint-everything adjoint under a switch
only if no listed routine executes -- itself, or through anything it calls -- a
statement that reads a switched variable. Such a routine, split, would carry the
forward sweep's value into its adjoint while its joint callees, and the
checkpoint-everything build, use the flipped one (runs 31156/31157 of the DINO
stability study are what that does). A split routine whose call tree is free
of switched variables records the same tape either way, because its inputs are
the same in both builds.

This script reads the preprocessed primal sources (*.f; Tapenade's *_b.f and
*_d.f are skipped) of an adjoint build directory, builds the static call graph
(CALL statements and references to any other program unit's name), marks the
units whose executable statements read a switched variable (declarations,
COMMON blocks and quoted strings do not count), and reports each listed routine.

    check_nocheckpoint_switches.py BUILD_DIR LIST_FILE        check a list
    check_nocheckpoint_switches.py BUILD_DIR LIST_FILE --filter=OUT
                                                  also write the switch-free
                                                  entries of LIST_FILE to OUT
    check_nocheckpoint_switches.py BUILD_DIR --all            classify every unit (TSV)

Options:
    --extra=NAME[,NAME]   further switched variables (the adjoint-viscosity
                          variant's inAd*/outAd* targets, say)

What it cannot see: a switched value passed as an argument by a routine that is
itself split is not traced (the argument has another name in the callee), and
calls through a variable procedure name are invisible. Both are absent from
the DINO call tree as far as the switched flags go, and the final check of any
list is a run bitwise identical to the checkpoint-everything build under the
switches it will be used with.

Exit status: 0 if every listed routine's call tree is free of switched
variables, 1 if not, 2 on a usage error.
"""
import os, re, sys
from collections import defaultdict, deque

# What pkg/autodiff/autodiff_inadmode_set_ad.F and _unset_ad.F change, plus the
# approximate-advection switch that is read together with inAdMode.
SWITCHED = {'INADMODE', 'USEKPP', 'USEGMREDI', 'USESEAICE', 'USEGGL90', 'USESALT_PLUME',
            'SEAICEUSEFREEDRIFT', 'SEAICEUSELSR', 'SEAICEUSEDYNAMICS', 'SEAICEADJMODE',
            'SINEGFAC', 'USEAPPROXADVECTIONINADMODE'}
DECL = ('COMMON', 'LOGICAL', 'INTEGER', 'REAL', 'DOUBLE', 'CHARACTER', 'COMPLEX', 'PARAMETER',
        'EXTERNAL', 'INTRINSIC', 'SAVE', 'DATA', 'NAMELIST', 'EQUIVALENCE', 'IMPLICIT',
        'DIMENSION', 'INCLUDE', 'BYTE')
UNIT_RE = re.compile(r'^(?:RECURSIVE\s+)?(?:(?:REAL|INTEGER|LOGICAL|DOUBLEPRECISION|CHARACTER|COMPLEX)'
                     r'[*\w()]*\s*)?(SUBROUTINE|FUNCTION|PROGRAM|BLOCKDATA)\s*([A-Z_]\w*)')


def statements(path):
    """Fixed-form statements of a preprocessed file, strings and comments removed, upper case."""
    stmts = []
    with open(path, errors='replace') as fh:
        for raw in fh:
            line = raw.rstrip('\n')
            if not line or line[0] in 'Cc*!#' or not line.strip():
                continue
            body = line[6:] if len(line) > 6 else ''
            body = re.sub(r"'[^']*'", "''", body)          # quoted strings
            body = re.sub(r'"[^"]*"', '""', body)
            body = body.split('!')[0]                      # trailing comment
            if len(line) > 5 and line[5] not in ' 0' and line[:5].strip() == '' and stmts:
                stmts[-1] += ' ' + body
            else:
                stmts.append(body)
    return [s.upper() for s in stmts]


def parse(build_dir):
    units = {}                  # name -> list of executable statements
    for f in sorted(os.listdir(build_dir)):
        if not f.endswith('.f') or f.endswith(('_b.f', '_d.f')):
            continue
        path = os.path.join(build_dir, f)
        with open(path, errors='replace') as fh:
            if 'Generated by TAPENADE' in fh.read(4000):      # adj_tap_all.f and the like
                continue
        cur = None
        for s in statements(path):
            compact = s.replace(' ', '')
            m = UNIT_RE.match(compact)
            if m and cur is None:
                # the compact form glues the argument list on; take the name from the spaced form
                name = re.match(r'[A-Z_]\w*', s.split(m.group(1), 1)[1].strip()).group(0)
                cur = units.setdefault(name, [])
                continue
            if cur is None:
                continue
            # END, END SUBROUTINE NAME ... -- but not ENDIF / ENDDO / END IF
            if re.fullmatch(r'END(\s+(SUBROUTINE|FUNCTION|PROGRAM)(\s+\w+)?)?', s.strip()):
                cur = None
                continue
            # declarations (and COMMON blocks from the expanded headers) are not reads;
            # an assignment such as DATAFILE = ... is, whatever its first letters
            if compact.startswith(DECL) and not re.match(r'[A-Z_]\w*(\([^=]*\))?=', compact):
                continue
            cur.append(s)
    return units


def analyse(units, switched):
    names = set(units)
    ident = re.compile(r'[A-Z_]\w*')
    calls, reads = defaultdict(set), {}
    for u, stmts in units.items():
        toks = set()
        for s in stmts:
            toks.update(ident.findall(s))
        reads[u] = sorted(toks & switched)
        calls[u] = (toks & names) - {u}
    return calls, reads


def path_to_switch(u, calls, reads):
    """Shortest call chain from u to a unit that reads a switched variable, or None."""
    seen, q = {u: None}, deque([u])
    while q:
        v = q.popleft()
        if reads.get(v):
            chain = [v]
            while seen[chain[-1]] is not None:
                chain.append(seen[chain[-1]])
            return list(reversed(chain)), reads[v]
        for w in sorted(calls.get(v, ())):
            if w not in seen:
                seen[w] = v
                q.append(w)
    return None


def main(argv):
    args = [a for a in argv[1:] if not a.startswith('--')]
    opts = [a for a in argv[1:] if a.startswith('--')]
    switched = set(SWITCHED)
    for o in opts:
        if o.startswith('--extra='):
            switched.update(x.strip().upper() for x in o.split('=', 1)[1].split(',') if x.strip())
    if not args or not os.path.isdir(args[0]):
        print(__doc__); return 2
    units = parse(args[0])
    calls, reads = analyse(units, switched)
    if '--all' in opts:
        print('unit\tswitch_free\treads\tvia')
        for u in sorted(units):
            p = path_to_switch(u, calls, reads)
            print(f"{u.lower()}\t{'yes' if p is None else 'no'}\t{','.join(reads[u]).lower()}\t"
                  f"{'' if p is None else ' > '.join(x.lower() for x in p[0])}")
        return 0
    if len(args) < 2:
        print(__doc__); return 2
    names = [re.sub(r'#.*', '', l).strip().upper() for l in open(args[1])]
    names = [n for n in names if n]
    filt = next((o.split('=', 1)[1] for o in opts if o.startswith('--filter=')), None)
    bad, kept = 0, []
    print(f'{len(units)} program units in {args[0]}; switched variables: {", ".join(sorted(x.lower() for x in switched))}')
    for n in names:
        if n not in units:
            print(f'  note  {n.lower()}: no primal source in the build directory'); continue
        p = path_to_switch(n, calls, reads)
        if p is None:
            print(f'  ok    {n.lower()}')
            kept.append(n.lower())
        else:
            bad = 1
            chain, rd = p
            print(f'  SWITCH {n.lower()}: {" > ".join(x.lower() for x in chain)} reads {", ".join(r.lower() for r in rd)}')
    if filt:
        with open(filt, 'w') as fh:
            fh.write('\n'.join(kept) + '\n')
        print(f'switch-free entries ({len(kept)} of {len(names)}) written to {filt}')
    print('OK: every listed routine has a switch-free call tree.' if not bad
          else 'FAIL: listed routines above reach a switched variable; keep them joint.')
    return bad


if __name__ == '__main__':
    sys.exit(main(sys.argv))
