#!/bin/bash
# Build the Tapenade ADJOINT with EVERY call checkpointed (Tapenade's default).
# THE DEFAULT DINO adjoint build since 2026-09-12: ./scripts/build_tapAdj.sh is a
# symlink to this file.
#   sources : code_tap/ + input_tap/  ->  build_tapAdj_ckpAll/mitgcmuv_tap_adj
#
# What adjoint it is comes from input_tap/data.autodiff, not from this build.
# DINO's is approximate by design: GM/Redi acts in the forward sweep only
# (useGMRediInAdMode=.FALSE.), and the flux-limited DST3 (scheme 33) is
# linearised as the unlimited DST3 (scheme 30) in the adjoint sweep
# (useApproxAdvectionInAdMode=.TRUE.); the submit body refuses an adjoint
# namelist without both unless IMPACTS_ALLOW_EXACT_ADJOINT=1
# (check_staged_namelists in scripts/setup_params.sh). Every DINO adjoint build
# compiles the scheme replacement -- mods_tapenade_hooks/gad_advection.F for the
# horizontal and explicit vertical fluxes, code_tap/gad_implicit_r.F for implicit
# vertical advection -- and the build body fails a build whose compiled sources
# lack it (COMPILED_NAME_CHECKS in setup_params.sh).
#
# History: from 2026-09-10 to 2026-09-12 the default was build_tapAdj_approxAdv.sh,
# this build plus gad_implicit_r.F from a variant directory (runs named
# tapAdj_ckpAll_approxAdv_*); with explicit vertical advection both gave the same
# adjoint (31263 vs 31259), and the builds merged when the file moved into
# code_tap/. From 2026-09-02 to 2026-09-10 it was build_tapAdj_nocheckpoint.sh,
# the same adjoint with the profile-guided -nocheckpoint list, and until
# 2026-09-02 this script WAS build_tapAdj.sh, so every run directory named
# tapAdj_ckpAll_* (and, before the 2026-09-02 scratch rename, plain tapAdj_*) up
# to job 31055 came from it.
#
# Checkpointing every call is also what the profiler build
# (build_tapAdj_profile.sh) measures, since a profile of the tuned build would
# only show the residual; the fallback when a configuration change invalidates
# the -nocheckpoint list; and the baseline for timing comparisons. A new list is
# validated against this build.
#
# Uses STOCK genmake2 and the tree's stock Tapenade options: the ADJ* dump
# calls are generated by Tapenade itself from the shared hooks directory,
# MITgcm_c69m/mods_tapenade_hooks/ (since 2026-09-07; its README says how),
# which the build body lists first in -mods and whose flow_tap it hands to
# Tapenade as a second -ext. Nothing in that directory is DINO-specific: its
# eight files (the seven of the hooks and, since 2026-09-12, gad_advection.F)
# serve SOMA and the barotropic gyre as well, and are, file for file, the
# upstream proposal.
# No generated file is post-edited.
#
# This file says WHAT to build; HOW is tools/lib/build_body.sh, shared by
# every build script (machine profile, genmake2, make, the generated-hook
# assertions listed in setup_params.sh, build_info.txt). Run from the setup
# directory: ./scripts/build_tapAdj_ckpAll.sh
# Pair with submit_tapAdj_ckpAll.sh.

set -euo pipefail
SETUP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

BUILD_DIR=build_tapAdj_ckpAll
BUILD_MODE=tapAdj
PARALLEL=mpi
MODS=(../code_tap)
TAP_EXTRA=""
CKP=ckpAll;     CKP_NOTE="every call inside a step checkpointed (Tapenade default)"
VARIANT=plain;  VARIANT_NOTE="code_tap/ alone: no variant directory, no profiler"
RUN_TOKEN=tapAdj_ckpAll

source "$SETUP_DIR/../../../tools/lib/build_body.sh"
