#!/bin/bash
# Build the Tapenade ADJOINT with EVERY call checkpointed (Tapenade's default).
#   sources : code_tap/ + input_tap/  ->  build_tapAdj_ckpAll/mitgcmuv_tap_adj
#
# This is the REFERENCE adjoint, not the default one. The default (what
# ./scripts/build_tapAdj.sh, a symlink, runs) was build_tapAdj_nocheckpoint.sh
# from 2026-09-02 -- the same adjoint with the profile-guided -nocheckpoint list
# added, bitwise identical in fc, adxx_* and ADJ* and 1.4-1.5x faster -- and is
# build_tapAdj_approxAdv.sh since 2026-09-10, this build plus the scheme swap
# for implicit vertical advection. Until 2026-09-02 this script WAS
# build_tapAdj.sh, so every run directory named tapAdj_ckpAll_* (and, before the
# 2026-09-02 scratch rename, plain tapAdj_*) up to job 31055 came from it.
#
# Keep it for what -nocheckpoint cannot do: it is what the profiler build
# (build_tapAdj_profile.sh) measures, since a profile of the tuned build
# would only show the residual; it is the fallback when a configuration change
# invalidates the routine list; and it is the baseline for timing comparisons.
# A new list is validated against it, or against the approxAdv build when the
# namelist needs that one.
#
# Uses STOCK genmake2 and the tree's stock Tapenade options: the ADJ* dump
# calls are generated by Tapenade itself from the shared hooks directory,
# MITgcm_c69m/mods_tapenade_hooks/ (since 2026-09-07; its README says how),
# which the build body lists first in -mods and whose flow_tap it hands to
# Tapenade as a second -ext. Nothing about the hooks is DINO-specific: the
# same seven files serve SOMA and are, file for file, the upstream proposal.
# No generated file is post-edited.
#
# This file says WHAT to build; HOW is tools/lib/build_body.sh, shared by
# every build script (machine profile, genmake2, make, the generated-hook
# assertions listed in setup_params.sh, build_info.txt). Run from the setup
# directory: ./scripts/build_tapAdj_ckpAll.sh
# Pair with submit_tapAdj_ckpAll.sh.

set -euo pipefail
SETUP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

BUILD_DIR=build_tapAdj_ckpAll
BUILD_MODE=tapAdj
PARALLEL=mpi
MODS=(../code_tap)
TAP_EXTRA=""
CKP=ckpAll;     CKP_NOTE="every call inside a step checkpointed (Tapenade default)"
VARIANT=plain;  VARIANT_NOTE="code_tap/ alone: no variant directory, no profiler"
RUN_TOKEN=tapAdj_ckpAll

source "$SETUP_DIR/../../../tools/lib/build_body.sh"
