#!/bin/bash
# Build the Tapenade ADJOINT. This is the one you normally want.
#   sources : code_tap/ + input_tap/  ->  build_tapAdj/mitgcmuv_tap_adj
#
# Uses STOCK genmake2 and the tree's stock Tapenade options: the ADJ* dump
# calls are generated by Tapenade itself from the shared hooks directory,
# MITgcm_c69m/mods_tapenade_hooks/ (since 2026-09-07; its README says how),
# which the build body lists first in -mods and whose flow_tap it hands to
# Tapenade as a second -ext. The same seven files serve DINO, so SOMA now
# carries the adjoint-mode switches as well; with the default data.autodiff
# they change no parameter. No generated file is post-edited.
#
# Every call is checkpointed (Tapenade's default): SOMA has no checkpointing
# profile yet, so unlike DINO's build_tapAdj.sh (a symlink to its tuned
# -nocheckpoint build) this is a real file and the plain adjoint. Its run
# token is tapAdj_ckpAll, the same vocabulary as DINO, so a tuned SOMA build
# can be told apart by name when one exists.
#
# SOMA's adjoint is serial-only: code_tap/SIZE.h is nPx=nPy=1 over
# sNx=sNy=62.
#
# This file says WHAT to build; HOW is tools/lib/build_body.sh, shared by
# every build script (machine profile, genmake2, make, the generated-hook
# assertions listed in setup_params.sh, build_info.txt). Run from the setup
# directory: ./scripts/build_tapAdj.sh   Pair with submit_tapAdj.sh.

set -euo pipefail
SETUP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

BUILD_DIR=build_tapAdj
BUILD_MODE=tapAdj
PARALLEL=serial
MODS=(../code_tap)
TAP_EXTRA=""
CKP=ckpAll;     CKP_NOTE="every call inside a step checkpointed (Tapenade default); SOMA has no -nocheckpoint profile yet"
VARIANT=plain;  VARIANT_NOTE="code_tap/ alone: no variant directory, no profiler"
RUN_TOKEN=tapAdj_ckpAll

source "$SETUP_DIR/../../../tools/lib/build_body.sh"
